use nc instead of whois

diff --git a/whois b/whois
--- a/whois
+++ b/whois
@@ -41,14 +41,16 @@ fi
 for domain in ${domains[@]}; do
 
     # [1] is the domain name is valid?
-    if [[ "$(echo "$domain" | grep -e '^[a-z0-9]\([a-z0-9\-]*[a-z0-9]\)\?\.\(com\|net\|org\|info\|biz\|us\|co.uk\|co\.kr\|ne\.kr\|or\.kr\|kr\)$')" != "$domain" ]]; then
-        echo "** ERROR: domain \"$domain\" not supported" 1>&2
-        continue
-    fi
+    #if [[ "$(echo "$domain" | grep -e '^[a-z0-9]\([a-z0-9\-]*[a-z0-9]\)\?\.\(com\|net\|org\|info\|biz\|us\|co.uk\|co\.kr\|ne\.kr\|or\.kr\|kr\)$')" != "$domain" ]]; then
+    #    echo "** ERROR: domain \"$domain\" not supported" 1>&2
+    #    continue
+    #fi
 
     # [2] whois lookup
     if [[ "$nocache" -ne 0 ]] || [[ ! -f "$cache_dir/$domain" ]]; then
-        # rate limit
+        #
+        # rate limiting
+        #
         case $domain in
         *.kr)
             if [[ "$(find "$cache_dir/" -name *.kr -ctime -1 | wc -l)" -gt 200 ]]; then
@@ -70,13 +72,38 @@ for domain in ${domains[@]}; do
             ;;
         esac
 
+        #
         # lookup
+        #
         case $domain in
         *.com|*.net)
-            whois --no-recursion $domain > "$cache_dir/$domain"
+            printf "=$domain\r\n" | nc whois.verisign-grs.com 43 > "$cache_dir/$domain"
+            ;;
+        *.org)
+            printf "$domain\r\n" | nc whois.pir.org 43 > "$cache_dir/$domain"
+            ;;
+        *.info)
+            printf "$domain\r\n" | nc whois.nic.info 43 > "$cache_dir/$domain" # whois.afilias.net ??
+            ;;
+        *.biz)
+            printf "$domain\r\n" | nc whois.biz 43 > "$cache_dir/$domain"
+            ;;
+        *.mobi)
+            printf "$domain\r\n" | nc whois.dotmobiregistry.net 43 > "$cache_dir/$domain"
+            ;;
+        *.edu)
+            printf "$domain\r\n" | nc whois.educause.edu 43 > "$cache_dir/$domain"
+            ;;
+        *.gov)
+            printf "$domain\r\n" | nc whois.nic.gov 43 > "$cache_dir/$domain"
+            ;;
+        *.kr)
+            printf "$domain\r\n" | nc whois.nic.or.kr 43 > "$cache_dir/$domain"
             ;;
         *)
-            whois $domain > "$cache_dir/$domain"
+            #whois $domain > "$cache_dir/$domain"
+            echo "** ERROR: domain \"$domain\" not supported" 1>&2
+            exit 1
             ;;
         esac
     fi
@@ -84,14 +111,18 @@ for domain in ${domains[@]}; do
     # recursion
     # must be either .com or .net
     if [[ "$recursion" -ne 0 ]] && [[ -n "$(echo "$domain" | grep -o '\.\(com\|net\)$')" ]]; then
-        rwhois="$(cat "$cache_dir/$domain" | grep "Registrar WHOIS Server:" | grep -o "[a-z0-9][a-z0-9\-\.]\+[a-z]$")"
+        #rwhois="$(cat "$cache_dir/$domain" | grep "Registrar WHOIS Server:" | grep -o "[a-z0-9][a-z0-9\-\.]\+[a-z]$")"
+        rwhois="$(cat "$cache_dir/$domain" \
+            | grep "Registrar WHOIS Server:" \
+            | sed -e 's/^[[:space:]]*Registrar\ WHOIS\ Server:[[:space:]]*//' -e 's/[\r\n]\+//' \
+            | tr -d '\n')"
         rcache_dir="$cache_dir/registrar-$rwhois-cache"
         rcache="$rcache_dir/$domain"
         if [[ "$nocache" -ne 0 ]] || [[ ! -f "$rcache" ]]; then
             if [[ ! -d "$rcache_dir" ]]; then
                 mkdir -p "$rcache_dir"
             fi
-            whois --host "$rwhois" "$domain" > "$rcache"
+            printf "$domain\r\n" | nc "$rwhois" 43 > "$rcache"
         fi
     fi
 
@@ -103,12 +134,17 @@ for domain in ${domains[@]}; do
         *.com|*.net)
             reg="$(cat "$cache_dir/$domain" | grep 'Creation Date:' | sed 's/^Creation\ Date:\ //' | grep -o "[0-9]\+-[0-9]\+-[0-9]\+")"
             ;;
-        *.org|*.info|*.biz|*.us)
+        *.org|*.info|*.biz|*.us|*.gov)
             reg="$(cat "$cache_dir/$domain" | grep 'Creation Date:' | sed 's/^Creation\ Date:\ //' | grep -o "[0-9]\+-[0-9]\+-[0-9]\+" | head -1)"
             ;;
         *.uk)
             reg="$(cat "$cache_dir/$domain" | grep 'Registered on:' | sed -e "s/^.\+\ before Aug-1996$/before 08-1996/" \
                 -e "s/^.\+\([0-9]\{2\}\)-\([A-Z][a-z]\{2\}\)-\([0-9]\{4\}\)/\3-\2-\1/" \
+                -e "s/\-Jan\-/\-01\-/" -e "s/\-Feb\-/\-02\-/" -e "s/\-Mar\-/\-03\-/" -e "s/\-Apr\-/\-04\-/" -e "s/\-May\-/\-05\-/" -e "s/\-Jun\-/\-06\-/" \
+                -e "s/\-Jul\-/\-07\-/" -e "s/\-Aug\-/\-08\-/" -e "s/\-Sep\-/\-09\-/" -e "s/\-Oct\-/\-10\-/" -e "s/\-Nov\-/\-11\-/" -e "s/\-Dec\-/\-12\-/")"
+            ;;
+        *.edu)
+            reg="$(cat "$cache_dir/$domain" | grep 'Domain expires:' | sed -e "s/^.\+\([0-9]\{2\}\)-\([A-Z][a-z]\{2\}\)-\([0-9]\{4\}\)/\3-\2-\1/" \
                 -e "s/\-Jan\-/\-01\-/" -e "s/\-Feb\-/\-02\-/" -e "s/\-Mar\-/\-03\-/" -e "s/\-Apr\-/\-04\-/" -e "s/\-May\-/\-05\-/" -e "s/\-Jun\-/\-06\-/" \
                 -e "s/\-Jul\-/\-07\-/" -e "s/\-Aug\-/\-08\-/" -e "s/\-Sep\-/\-09\-/" -e "s/\-Oct\-/\-10\-/" -e "s/\-Nov\-/\-11\-/" -e "s/\-Dec\-/\-12\-/")"
             ;;
@@ -152,7 +188,11 @@ for domain in ${domains[@]}; do
         case $domain in
         *.com|*.net)
             cat "$cache_dir/$domain"
-            rwhois="$(cat "$cache_dir/$domain" | grep "Registrar WHOIS Server:" | grep -o "[a-z0-9][a-z0-9\-\.]\+[a-z]$")"
+            #rwhois="$(cat "$cache_dir/$domain" | grep "Registrar WHOIS Server:" | grep -o "[a-z0-9][a-z0-9\-\.]\+[a-z]$")"
+            rwhois="$(cat "$cache_dir/$domain" \
+                | grep "Registrar WHOIS Server:" \
+                | sed -e 's/^[[:space:]]*Registrar\ WHOIS\ Server:[[:space:]]*//' -e 's/[\r\n]\+//' \
+                | tr -d '\n')"
             rcache_dir="$cache_dir/registrar-$rwhois-cache"
             rcache="$rcache_dir/$domain"
             if [[ -f "$rcache" ]]; then
